# Generated by Django 3.2.4 on 2024-05-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20240519_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='administrationVerified',
            field=models.BooleanField(default=True, verbose_name='Подтверждение админа'),
        ),
    ]
